<?php
/**
 * Admin configuration — credentials and shared settings.
 */

/* ---------- Login credentials ---------- */

// Username (plain text — usernames aren't secret)
const ADMIN_USERNAME = 'Admin';

// Password HASH — generated by password_hash('FeteCation#2026!Ride', PASSWORD_DEFAULT)
// You will never store the plain password in this file.
const ADMIN_PASSWORD_HASH = '$2y$10$mk4LSgU6btWK9dKgark6Ie3BOprJb6KZhw0dIWzrRYxSrk.kj11oG';

/* ---------- Paths ---------- */

// Where bookings and messages live (relative to the site root)
define('ADMIN_SITE_ROOT',   dirname(__DIR__));
define('ADMIN_BOOKINGS_DIR', ADMIN_SITE_ROOT . '/data/bookings');
define('ADMIN_MESSAGES_DIR', ADMIN_SITE_ROOT . '/data/messages');